#
name: Main CI
#
on:
  push:
    branches:      
      - "next"
      - "next-major"
  pull_request:
    branches:
      - "main"
      - "next"
      - "next-major"
  workflow_dispatch:
env:
  DOCKER_REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/containers/${{ github.event.repository.name }}
permissions:
  contents: read # for actions/checkout to fetch code  

jobs:
  lint-hado:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  checkov:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
         
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        version:
          - base
          - kafka
          - all
    needs: 
      - release
    steps:
      - name: checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY_IMAGE }}
          flavor: |
            latest=false
            prefix=${{ matrix.version }}_
          tags: |
            type=sha,format=long
            type=sha
            type=semver,pattern={{version}},value=${{ needs.release.outputs.version }}
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
          labels: |
            org.opencontainers.image.licenses=Apache-2.0              
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.DOCKER_REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          build-args: |
            PROFILE=${{ matrix.version }}
      - name: Export digest
        run: |
          mkdir -p /tmp/digests/${{ matrix.version }}
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${{ matrix.version }}/${digest#sha256:}"          
      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
              
  release:
    runs-on: ubuntu-latest
    needs: 
      - lint-hado
      - checkov
    permissions:
      contents: write
      issues: write
    outputs:
      version: ${{ steps.version.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Semantic Release
        id: version
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@8.1.0
            @semantic-release/changelog@6.0.3
            conventional-changelog-conventionalcommits@6.1.0
            @semantic-release/exec@6.0.3             
         
  docker-merge:
    runs-on: ubuntu-latest
    needs: 
      - docker
      - release
    permissions:
      packages: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - base
          - kafka
          - all
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          name: digests
          path: /tmp/digests/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY_IMAGE }}
          flavor: |
            latest=false
            prefix=${{ matrix.version }}_
          tags: |
            type=sha,format=long,prefix=${{ matrix.version }}_
            type=sha,pattern={{version}},value=${{ needs.release.outputs.version }},prefix=${{ matrix.version }}_
            type=semver,pattern={{version}},value=${{ needs.release.outputs.version }},prefix=${{ matrix.version }}_
            type=ref,event=branch,prefix=${{ matrix.version }}_
            type=ref,event=pr,prefix=${{ matrix.version }}_
            type=ref,event=tag,prefix=${{ matrix.version }}_
          labels: |
            org.opencontainers.image.licenses=Apache-2.0          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}          
      - name: Create manifest list and push
        working-directory: /tmp/digests/${{ matrix.version }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKER_REGISTRY_IMAGE }}@sha256:%s ' *)          
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}                